apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "7472"
    prometheus.io/scrape: "true"
  name: prod-pool
  namespace: metallb
spec:
  addresses:
  - 127.0.0.240/28
  autoAssign: true
  avoidBuggyIPs: false
