apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: metallb
  namespace: metallb
  releaseName: metallb
  repo: https://metallb.github.io/metallb
  version: 0.14.3

namespace: metallb
resources:
- namespace.yaml
- ip-pool.yaml
- l2-advert.yaml
