apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  labels:
    application: certmanager
    component: ingress
    team: operations
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: pdorczuk@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret
          email: pdorczuk@gmail.com
      selector:
        dnsNames:
        - echesec.com
        - '*.echesec.com'
        dnsZones:
        - echesec.com
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8000"
    prometheus.io/scrape: "true"
  labels:
    application: certmanager
    component: ingress
    team: operations
  name: letsencrypt-stage
  namespace: cert-manager
spec:
  acme:
    email: pdorczuk@gmail.com
    privateKeySecretRef:
      name: letsencrypt-stage
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: api-token
            name: cloudflare-api-token-secret
          email: pdorczuk@gmail.com
      selector:
        dnsZones:
        - echesec.com
