apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: cert-manager
  namespace: cert-manager
  valuesFile: values.yaml  
  releaseName: certmanager
  repo: https://charts.jetstack.io
  version: 1.11.1

namespace: cert-manager
resources:
- namespace.yaml
- cluster-issuer.yaml
- external-secret.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.11.1/cert-manager.crds.yaml
