apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: ingress-nginx
  namespace: nginx
  releaseName: nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.9.1

namespace: nginx
resources:
- namespace.yaml
