apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- includeCRDs: true
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
  releaseName: nfs-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  valuesFile: values.yaml
  version: 4.0.18

namespace: nfs-provisioner
resources:
- namespace.yaml

commonAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "8000"
  prometheus.io/scrape: "true"
labels:
- includeSelectors: true
  pairs:
    team: operations
